pen-lang/pen

- features/types/none.feature
- lib/lang/src/hir_mir/expression_compiler.rs
- lib/lang/src/hir_mir/module_compiler.rs
- lib/lang/src/hir_mir/type_compiler.rs
- lib/mir-fmm/src/expressions.rs
- lib/mir-fmm/src/reference_count/expressions.rs
- lib/mir-fmm/src/types.rs
- lib/mir/src/analysis/environment_inference.rs
- lib/mir/src/analysis/free_variables.rs
- lib/mir/src/analysis/reference_count/mod.rs
- lib/mir/src/analysis/type_check/mod.rs
- lib/mir/src/analysis/variant_type_collection.rs
- lib/mir/src/ir/expression.rs
- lib/mir/src/types/type_.rs
> None type in MIR

- lib/app/src/infra/file_path.rs
- lib/app/src/module_compiler/mod.rs
> Module prefixes of relative paths

- doc/assets/index.scss
- doc/layouts/_default/baseof.html
- doc/layouts/index.html
- doc/static/icon.svg
- doc/static/manifest.json
> Temporary icon

- Cargo.lock
- features/standard-packages/os.feature
- lib/ffi/Cargo.toml
- lib/ffi/src/arc/mod.rs
- lib/os/Os.pen
- lib/os/ffi/src/array.rs
- lib/os/ffi/src/directory.rs
- lib/os/ffi/src/file.rs
- lib/os/ffi/src/lib.rs
- lib/os/ffi/src/result.rs
- lib/os/ffi/src/utilities.rs
> Directory API

- lib/lang/src/hir/analysis/expression_visitor.rs
- lib/lang/src/hir/analysis/mod.rs
- lib/lang/src/hir_mir/error.rs
- lib/lang/src/hir_mir/generic_type_definition_compiler.rs
- lib/lang/src/hir_mir/mod.rs
- lib/lang/src/hir_mir/record_element_validator.rs
> Record element validation

- cmd/pen/src/file_path_configuration.rs
- cmd/pen/src/infrastructure.rs
- lib/app/src/error.rs
- lib/app/src/infra/application_linker.rs
- lib/app/src/lib.rs
- lib/app/src/package_build_script_compiler/mod.rs
- lib/app/src/package_builder.rs
- lib/infra/src/application_linker.rs
- lib/infra/src/error.rs
- lib/infra/src/package_script_finder.rs
- lib/lang/src/hir_mir/mod.rs
- lib/os/pen-link.sh
> Application linker in system package

- lib/lang/src/hir_mir/error.rs
- lib/lang/src/hir_mir/mod.rs
- lib/lang/src/hir_mir/try_operation_validator.rs
> Type check for invalid try operation

- lib/lang/src/parse/attempt.rs
- lib/lang/src/parse/mod.rs
- lib/lang/src/parse/parsers.rs
> Fix parse errors

- doc/src/guides/install.md
> Add dependency instructions

- features/standard-packages/os.feature
- lib/os/Context.pen
- lib/os/File.pen
- lib/os/ffi/src/file.rs
> Move files

- doc/book.toml
- doc/src/references/language/syntax.md
- doc/theme/custom-highlight.js
> Highlight syntax in documentation

- lib/parse/src/parsers.rs
- lib/parse/src/snapshots/parse__parsers__tests__expressions__call__fail_to_parse_call.snap
- lib/parse/src/utilities.rs
> Fix suffix operator parser error messages

- doc/src/references/language/syntax.md
> Document function expressions

- lib/app/src/error.rs
- lib/app/src/module_dependency_resolver.rs
- lib/infra/src/file_path_displayer.rs
> Comprehensive module import error

- features/package.feature
- lib/hir-mir/src/lib.rs
- lib/hir-mir/src/type_context.rs
- lib/hir/src/analysis/types.rs
- lib/hir/src/analysis/types/type_collector.rs
- lib/hir/src/analysis/types/type_existence_validator.rs
> Validate type existence

- Cargo.lock
- cmd/pen/Cargo.toml
> Bump version

- lib/hir-mir/src/module_compiler.rs
- lib/mir-fmm/src/closures.rs
- lib/mir-fmm/src/entry_functions.rs
- tools/check_memory_leak_in_loop.sh
- tools/utilities.sh
> Drop thunk environments when they are forced

- examples/README.md
- examples/life-game/README.md
- examples/life-game/lifeGame.pen
- examples/life-game/lifeGame.test.pen
- examples/life-game/main.pen
- examples/life-game/pen.json
- features/smoke/examples.feature
> Life game example

- cmd/pen/src/file_path_configuration.rs
- doc/src/references/language/packages.md
- doc/src/references/standard-packages/core.md
- doc/src/references/standard-packages/os.md
- doc/src/references/standard-packages/test.md
- examples/cat/pen.json
- examples/console/pen.json
- examples/echo/pen.json
- examples/hello-world/pen.json
- examples/life-game/pen.json
- examples/ls/pen.json
- examples/tcp-client/pen.json
- examples/tcp-server/pen.json
- examples/udp-client/pen.json
- examples/udp-server/pen.json
- examples/yes/pen.json
- features/commands/build.feature
- features/commands/test.feature
- features/smoke/function.feature
- features/smoke/list.feature
- features/smoke/memory_leak.feature
- features/smoke/string.feature
- features/smoke/test.feature
- features/smoke/union.feature
- features/standard-packages/core.feature
- features/standard-packages/os.feature
- features/standard-packages/test.feature
- features/types/stream.feature
- lib/infra/src/external_package_initializer.rs
- Change library paths
- Fix build
> Library path changes

- Cargo.lock
- cmd/test/Cargo.lock
- cmd/test/src/test_result.rs
- lib/ffi/Cargo.toml
- lib/ffi/src/any.rs
- lib/ffi/src/number.rs
- lib/ffi/src/string.rs
- lib/mir-fmm/src/expressions.rs
- lib/mir-fmm/src/reference_count/expressions.rs
- lib/mir-fmm/src/reference_count/functions.rs
- lib/mir-fmm/src/reference_count/pointers.rs
- lib/mir-fmm/src/reference_count/record_utilities.rs
- lib/mir-fmm/src/reference_count/records.rs
- lib/mir-fmm/src/reference_count/variants.rs
- lib/mir-fmm/src/types.rs
- lib/mir/src/types/record_body.rs
- lib/os/ffi/Cargo.lock
- lib/os/ffi/src/string_array.rs
- tools/check_memory_leak_in_loop.sh
- tools/update_ffi_crate.sh
> Clone functions compatible with Rust FFI

- features/smoke/memory_leak.feature
- lib/mir-fmm/src/entry_functions.rs
> Fix memory leak with forced elements in lists

- features/types/union.feature
- lib/hir-mir/src/expression_compiler.rs
- lib/hir-mir/src/generic_type_definition_compiler.rs
- lib/hir-mir/src/type_compiler.rs
> Upcast functions

- features/types/polymorphism.feature
- lib/hir-mir/src/error.rs
- lib/hir-mir/src/type_checker.rs
> Fix incomparable equal operation types

- lib/os-sync/ffi/application/src/main.rs
- lib/os-sync/ffi/application/src/spawn.rs
- lib/os/ffi/application/src/main.rs
- lib/os/ffi/application/src/spawn.rs
This reverts commit bcaac2fa0b15f6b5885d5c650b124d1bcd40b5d8.
> Spawn functions in os packages

- cmd/pen/src/infrastructure.rs
- lib/app/src/infra/file_path.rs
- lib/infra/src/ninja_build_script_compiler.rs
> Convert file paths in build files

- examples/life-game/lifeGame.pen
- lib/core/Number.pen
- Add range functions
- Refactor life game
> Refactor examples with list comprehension

- lib/os-sync/ffi/Cargo.lock
- lib/os-sync/ffi/application/Cargo.toml
- lib/os-sync/ffi/application/src/utilities.rs
- lib/os/ffi/application/src/utilities.rs
- Fix performance of debug environment variable check
- Fix performance in os package
> Environment variable check performance bug in `os` packages

- tools/integration_test.sh
> Disable retry in integration tests

- features/smoke/memory_leak.feature
> Less flaky memory leak tests

- lib/core/Map.pen
- lib/core/Map/hamt.pen
- lib/core/Map/stringMap.pen
- lib/core/Map/stringMap.test.pen
> Map iteration

- lib/core/Map.pen
- lib/core/Map/stringMap.pen
- lib/core/Map/stringMap.test.pen
- Add merge function
- Test merge function
> `Merge` function in `Map` module

- features/smoke/list.feature
- lib/hir-mir/src/expression_compiler.rs
> Lazy evaluation in list comprehension

- Cargo.lock
- cmd/test/Cargo.lock
- lib/core/ffi.pen
- lib/core/ffi/Cargo.lock
- lib/core/ffi/src/string.rs
- lib/ffi/Cargo.toml
- lib/ffi/src/box_any.rs
- lib/hir-mir/src/downcast_compiler.rs
- lib/hir-mir/src/error.rs
- lib/hir-mir/src/lib.rs
- lib/hir-mir/src/type_checker.rs
- lib/hir-mir/src/validation.rs
- lib/hir-mir/src/validation/duplicate_function_name_validator.rs
- lib/hir-mir/src/validation/duplicate_type_name_validator.rs
- lib/hir-mir/src/validation/ffi_variant_type_validator.rs
- lib/hir-mir/src/validation/record_field_validator.rs
- lib/hir-mir/src/validation/try_operation_validator.rs
- lib/hir/src/types/type_.rs
- lib/os-sync/ffi/Cargo.lock
- lib/os/ffi/Cargo.lock
- lib/prelude/ffi/Cargo.lock
> Union and any type use validation in FFI

- lib/hir-mir/src/generic_type_definition_compiler.rs
- lib/hir-mir/src/transformation/map_literal_transformer.rs
- lib/hir/src/analysis/type_equality_checker.rs
- lib/hir/src/analysis/type_id_calculator.rs
- lib/hir/src/analysis/union_type_member_calculator.rs
- lib/prelude/Map.pen
- tools/lint.sh
- tools/utilities.sh
> Fix generic type collection for map expressions

- lib/format/src/lib.rs
> Code formatter improvements

- examples/algorithms/fizz-buzz/main.pen
- examples/algorithms/knapsack/main.pen
- examples/algorithms/quick-sort/main.pen
- lib/format/src/ir/build.rs
- lib/format/src/ir/document.rs
- lib/format/src/ir/format.rs
- lib/format/src/ir/utils.rs
- lib/format/src/lib.rs
> Fix parent node break in code formatter

- .cspell.json
- Cargo.lock
- Cargo.toml
- cmd/pen/src/main.rs
- cmd/pen/src/package_documentation_generator.rs
- features/commands/document.feature
- lib/app/Cargo.toml
- lib/app/src/common/file_path_resolver.rs
- lib/app/src/lib.rs
- lib/app/src/module_formatter.rs
- lib/app/src/package_documentation_generator.rs
- lib/ast-hir/src/module_compiler.rs
- lib/ast/src/analysis.rs
- lib/ast/src/ast/type_definition.rs
- lib/core/Bit.pen
- lib/doc/Cargo.toml
- lib/doc/src/ir.rs
- lib/doc/src/ir/build.rs
- lib/doc/src/ir/document.rs
- lib/doc/src/lib.rs
- lib/doc/src/markdown.rs
- lib/format/src/ir/build.rs
- lib/format/src/lib.rs
> Documentation generator

- examples/http-server/main.pen
- packages/http/Context/context.pen
- packages/http/Context/ffiResponse.pen
- packages/http/Response.pen
- packages/http/ffi/src/client.rs
- packages/http/ffi/src/header_map.rs
- packages/http/ffi/src/response.rs
- packages/http/ffi/src/server.rs
> HTTP headers in responses

- Cargo.lock
- cmd/test/Cargo.lock
- features/smoke/standard-packages.feature
- lib/ffi/Cargo.toml
- lib/ffi/src/box_any.rs
- lib/ffi/src/cps.rs
- lib/ffi/src/cps/import.rs
- lib/ffi/src/future.rs
- lib/ffi/src/future/call.rs
- lib/ffi/src/future/call_function.rs
- lib/ffi/src/future/from_closure.rs
- lib/ffi/src/future/from_function.rs
- lib/ffi/src/list.rs
- packages/core/ffi/Cargo.lock
- packages/ffi/any.pen
- packages/ffi/list.pen
- packages/ffi/pen.json
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/application/src/main.rs
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
> `Ffi` package

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi/Cargo.toml
- packages/core/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/http/ffi/Cargo.toml
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/application/Cargo.toml
- packages/os/ffi/library/Cargo.lock
- packages/os/ffi/library/Cargo.toml
- packages/prelude/ffi/Cargo.lock
> Enable HTTP 2.0

- .github/dependabot.yml
- doc/src/SUMMARY.md
- examples/algorithms/quick-sort/main.pen
- features/smoke/os.feature
- features/standard-packages/os-sync.feature
- features/standard-packages/os.feature
- lib/app/src/module_compiler.rs
- lib/ast-hir/src/import_compiler.rs
- lib/ast-hir/src/lib.rs
> Fix automatic imports of context modules

- Cargo.lock
- cmd/test/Cargo.lock
- cmd/test/Cargo.toml
- lib/ffi/Cargo.toml
- lib/ffi/src/arc/arc_block.rs
- lib/mir-fmm/src/reference_count.rs
- lib/mir-fmm/src/reference_count/count.rs
- lib/mir-fmm/src/reference_count/heap.rs
- lib/mir-fmm/src/reference_count/pointer.rs
- lib/mir-fmm/src/snapshots/mir_fmm__entry_function__tests__do_not_overwrite_global_functions_in_variables.snap
- packages/core/ffi/Cargo.lock
- packages/core/ffi/Cargo.toml
- packages/http/ffi/Cargo.lock
- packages/http/ffi/Cargo.toml
- packages/json/ffi/Cargo.lock
- packages/json/ffi/Cargo.toml
- packages/os-sync/ffi/Cargo.lock
- packages/os-sync/ffi/application/Cargo.toml
- packages/os-sync/ffi/library/Cargo.toml
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/application/Cargo.toml
- packages/os/ffi/library/Cargo.lock
- packages/os/ffi/library/Cargo.toml
- packages/sql/ffi/Cargo.lock
- packages/sql/ffi/Cargo.toml
For atomic reference counting optimization described in #468.
> 32 bit count in reference counting

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi/Cargo.toml
- lib/ffi/src/arc/arc_block.rs
- lib/mir-fmm/src/reference_count/count.rs
- lib/mir-fmm/src/reference_count/heap.rs
- lib/mir-fmm/src/reference_count/pointer.rs
- lib/mir-fmm/src/snapshots/mir_fmm__entry_function__tests__do_not_overwrite_global_functions_in_variables.snap
- packages/core/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
- packages/prelude/ffi/Cargo.toml
- packages/sql/ffi/Cargo.lock
> Refactor memory block header structure

- features/types/record.feature
- lib/hir/src/analysis/record_field_validator.rs
> Propagate record type openness

- lib/ffi/src/closure.rs
- lib/mir-fmm/src/call.rs
- lib/mir-fmm/src/reference_count/pointer.rs
> Review atomic operations

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi/Cargo.toml
- lib/mir-fmm/src/expression.rs
- lib/mir-fmm/src/reference_count/pointer.rs
- packages/core/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
- packages/sql/ffi/Cargo.lock
> Bump `ffi` crate version

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi/Cargo.toml
- lib/ffi/src/arc.rs
- lib/ffi/src/arc/arc_block.rs
- lib/mir-fmm/src/reference_count/count.rs
- lib/mir-fmm/src/reference_count/heap.rs
- lib/mir-fmm/src/reference_count/pointer.rs
- packages/core/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
- packages/sql/ffi/Cargo.lock
> Change synchronized unique counts

- lib/app/src/infra/file_path.rs
- lib/hir-mir/src/expression.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_extractor.rs
- lib/infra/src/test_linker.rs
- lib/mir-fmm/src/entry_function.rs
- lib/mir-fmm/src/reference_count/pointer.rs
- lib/mir/src/analysis/reference_count/validation.rs
> Relaxed atomic operations for thunks

- lib/hir/src/analysis.rs
- lib/hir/src/analysis/error.rs
- lib/hir/src/analysis/impossible_type_validator.rs
- lib/hir/src/analysis/nonexistent_type_validator.rs
- lib/hir/src/analysis/record_field_resolver.rs
- lib/hir/src/analysis/record_field_validator.rs
- lib/hir/src/analysis/type_resolver.rs
> Recursive record type validation for type domination

- .github/workflows/test.yaml
- features/commands/test.feature
- features/smoke/examples.feature
- features/smoke/standard-packages.feature
- features/smoke/test.feature
- tools/pen_test_on_linux.sh
> Enable integration tests on macOS

- doc/src/guides/concurrency-and-parallelism.md
- doc/src/references/language/built-ins.md
- doc/src/references/language/syntax.md
- features/smoke/memory-leak/concurrency.feature
- features/smoke/memory-leak/language.feature
- features/smoke/os.feature
- features/syntax/concurrency.feature
- lib/ast-hir/src/module.rs
- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/expression.rs
- lib/hir-mir/src/generic_type_definition.rs
- lib/hir-mir/src/module.rs
- lib/hir-mir/src/type_.rs
- lib/hir/src/analysis/error.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_extractor.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/hir/src/ir/built_in_call.rs
- lib/parse/src/parsers.rs
- lib/parse/src/snapshots/parse__parsers__tests__expressions__call__fail_to_parse_call.snap
- Part of #1085.
- Related to #1083.
> Go built-in function

- packages/core/Number.pen
- packages/core/Number.test.pen
- packages/core/ffi/src/number.rs
> More functions in `Core'Number` module

- Cargo.lock
- lib/ffi/Cargo.toml
- lib/ffi/src/list.rs
- packages/core/Number.pen
- packages/core/String/Utf8.pen
- packages/core/String/Utf8.test.pen
- packages/core/ffi/Cargo.lock
- packages/core/ffi/src/string/utf8.rs
> More string functions in `Core'String` module

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi/Cargo.toml
- lib/ffi/src/cps/import.rs
- lib/ffi/src/future/stream.rs
- packages/core/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/application/src/main.rs
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
- packages/sql/ffi/Cargo.lock
> `async fn` generation by `import!` macro in FFI

- packages/core/Character.pen
- packages/core/Character.test.pen
- packages/core/ffi/src/character.rs
- packages/core/ffi/src/lib.rs
- packages/html/Render.pen
- packages/html/Render.test.pen
- packages/html/validate.pen
- packages/html/validate.test.pen
> Validate tag names and attribute keys in `Html` package

- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/downcast.rs
- lib/hir-mir/src/expression.rs
- lib/hir-mir/src/module.rs
- lib/hir-mir/src/transformation/equal_operation.rs
- lib/hir-mir/src/transformation/hash_calculation.rs
- lib/hir/src/analysis/error.rs
- lib/hir/src/analysis/record_field_resolver.rs
- lib/hir/src/analysis/record_field_validator.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_coercer.rs
- lib/hir/src/analysis/type_comparability_checker.rs
- lib/hir/src/analysis/type_extractor.rs
- lib/hir/src/analysis/type_formatter.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/position/src/format.rs
- lib/position/src/lib.rs
- lib/position/src/position.rs
> Show types in error messages

- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/expression.rs
- lib/hir-mir/src/module.rs
- lib/hir-mir/src/transformation/record_equal_function.rs
- lib/hir-mir/src/transformation/record_hash_function.rs
- lib/mir-fmm/src/entry_function.rs
- lib/mir-fmm/src/function_definition.rs
- lib/mir-fmm/src/lib.rs
- lib/mir/src/analysis/environment_inference.rs
- lib/mir/src/analysis/lambda_lifting.rs
- lib/mir/src/analysis/lambda_lifting/context.rs
- lib/mir/src/analysis/reference_count/transformation.rs
- lib/mir/src/analysis/reference_count/validation.rs
- lib/mir/src/analysis/type_check.rs
- lib/mir/src/analysis/type_check/name.rs
- lib/mir/src/analysis/variant_type_collection.rs
- lib/mir/src/ir/function_definition.rs
- lib/mir/src/test/ir.rs
- lib/mir/src/test/ir/function_definition.rs
> Visibility in MIR

- packages/json/Decode.pen
- packages/json/Decode.test.pen
> Refactor JSON package

- Cargo.lock
- lib/mir-fmm/src/lib.rs
- lib/mir/Cargo.toml
- lib/mir/src/analysis.rs
- lib/mir/src/analysis/alpha_conversion.rs
- lib/mir/src/analysis/alpha_conversion/context.rs
- lib/mir/src/analysis/normalization.rs
- lib/mir/src/analysis/normalization/alias_removal.rs
- lib/mir/src/analysis/normalization/context.rs
> ANF in MIR

- examples/snake/entity.pen
- examples/snake/main.pen
- examples/snake/render.test.pen
- features/smoke/module.feature
- lib/hir-mir/src/lib.rs
- lib/hir-mir/src/transformation/record_equal_function.rs
- lib/hir-mir/src/transformation/record_hash_function.rs
> Fix comparison of types imported indirectly

- features/smoke/module.feature
- features/smoke/syntax.feature
- lib/ast-hir/src/error.rs
- lib/ast-hir/src/import.rs
- lib/ast-hir/src/imported_module.rs
- lib/ast-hir/src/imported_module/validation.rs
- lib/ast-hir/src/lib.rs
- lib/ast/src/ast.rs
- lib/ast/src/ast/import.rs
- lib/ast/src/ast/unqualified_name.rs
- lib/format/src/lib.rs
- lib/parse/src/parsers.rs
- packages/html/Render.pen
> Errors for undefined unqualified imports

- doc/docs/references/command-line-tools.md
- doc/mkdocs.yaml
> Fix styles in documentation

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi/Cargo.toml
- packages/core/ffi/Cargo.lock
- packages/html/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
- packages/random/ffi/Cargo.lock
- packages/regex/ffi/Cargo.lock
- packages/sql/ffi/Cargo.lock
> Bump version of `ffi` crate

- cmd/test/src/debug.rs
- packages/os-sync/ffi/application/src/debug.rs
- packages/os/ffi/application/src/debug.rs
> Refactor `debug` functions

- Cargo.lock
- cmd/test/Cargo.lock
- lib/ffi-macro/Cargo.toml
- lib/ffi-macro/src/any.rs
- lib/ffi/Cargo.toml
- lib/ffi/src/any.rs
- lib/ffi/src/lib.rs
- lib/ffi/src/type_information.rs
- packages/core/ffi/Cargo.lock
- packages/html/ffi/Cargo.lock
- packages/http/ffi/Cargo.lock
- packages/json/ffi/Cargo.lock
- packages/os-sync/ffi/Cargo.lock
- packages/os/ffi/application/Cargo.lock
- packages/os/ffi/library/Cargo.lock
- packages/prelude/ffi/Cargo.lock
- packages/random/ffi/Cargo.lock
- packages/regex/ffi/Cargo.lock
- packages/sql/ffi/Cargo.lock
> Fix FFI for new type information format

- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/error.rs
- lib/hir-mir/src/module.rs
- lib/hir-mir/src/snapshots/hir_mir__built_in_call__tests__compile_debug.snap
- lib/hir-mir/src/type_information.rs
- lib/hir-mir/src/type_information/debug.rs
> Extendable type information function

- lib/hir-mir/src/error_type.rs
> Prevent nested `error`s

- features/smoke/built-ins.feature
- lib/ast-hir/src/import.rs
- lib/ast-hir/src/type_.rs
- lib/format/src/lib.rs
- lib/hir-mir/src/expression.rs
- lib/hir-mir/src/lib.rs
- lib/hir-mir/src/main_function.rs
- lib/hir-mir/src/transformation/equal_operation/operation.rs
- lib/hir-mir/src/transformation/hash_calculation/expression.rs
- lib/hir-mir/src/transformation/record_equal_function.rs
- lib/hir-mir/src/transformation/record_hash_function.rs
- lib/hir-mir/src/type_information.rs
- lib/hir-mir/src/type_information/debug.rs
- lib/hir/src/analysis/impossible_type_validator.rs
- lib/hir/src/analysis/record_field_validator.rs
- lib/hir/src/analysis/type_coercer.rs
- lib/hir/src/analysis/type_collector.rs
- lib/hir/src/analysis/type_comparability_checker.rs
- lib/hir/src/analysis/type_equality_checker.rs
- lib/hir/src/analysis/type_existence_validator.rs
- lib/hir/src/analysis/type_formatter.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/hir/src/analysis/type_qualifier.rs
- lib/hir/src/test.rs
- lib/hir/src/test/ir/type_definition.rs
- lib/hir/src/test/types.rs
- lib/hir/src/test/types/record.rs
- lib/hir/src/types/record.rs
- lib/parse/src/parsers.rs
- test/reflect/any.test.pen
> Original record names in error messages and reflection

- lib/infra/src/ninja_build_script_compiler.rs
> Fix FFI module rebuild

- lib/hir/src/analysis/type_canonicalizer.rs
```
> hyperfine '~/src/github.com/pen-lang/pen/target/release/pen compile-prelude --target aarch64-apple-darwin /Users/raviqqe/worktree/2384c198b563320e/examples/life-game/.pen/default/packages/pen_prelude/Map.pen /Users/raviqqe/worktree/2384c198b563320e/examples/life-game/.pen/default/objects/Map_eca1efc0cf2dc7fa.bc /Users/raviqqe/worktree/2384c198b563320e/examples/life-game/.pen/default/objects/Map_eca1efc0cf2dc7f' '~/worktree/af75feaf2623cef4/target/release/pen compile-prelude --target aarch64-apple-darwin /Users/raviqqe/worktree/2384c198b563320e/examples/life-game/.pen/default/packages/pen_prelude/Map.pen /Users/raviqqe/worktree/2384c198b563320e/examples/life-game/.pen/default/objects/Map_eca1efc0cf2dc7fa.bc /Users/raviqqe/worktree/2384c198b563320e/examples/life-game/.pen/default/objec …
```
> Optimize type canonicalization

- doc/docs/references/language/built-ins.md
- packages/core/String.pen
- packages/core/String.test.pen
- packages/core/String/Byte/View.pen
- packages/core/String/Byte/View.test.pen
- packages/core/String/Utf8.pen
- packages/core/String/Utf8.test.pen
- packages/core/ffi/src/string.rs
- packages/core/ffi/src/string/utf8.rs
- packages/core/ffi/src/view.rs
- packages/flag/Flag.pen
- packages/html/validate.pen
- packages/json/Decode.pen
- packages/regex/Expression.pen
- packages/regex/Expression.test.pen
- packages/regex/ffi/src/lib.rs
> Rename inconsistent library functions

- .cspell.json
- lib/infra/src/ninja_build_script_runner.rs
> Clean dead outputs first

- Cargo.lock
- lib/ast/src/ast/argument.rs
- lib/ast/src/types/record_field.rs
- lib/doc/src/lib.rs
- lib/format/Cargo.toml
- lib/format/src/lib.rs
- lib/parse/src/parser.rs
> Bug fixes for formatter

- features/types/map.feature
- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/lib.rs
- lib/hir-mir/src/type_.rs
- lib/hir/src/analysis/built_in_variable_transformer.rs
- lib/hir/src/analysis/error.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/hir/src/ir/built_in_function.rs
> `delete` built-in function

- features/smoke/test.feature
- lib/app/src/common/file_path_resolver.rs
- lib/app/src/infra/build_script_compiler.rs
- lib/app/src/infra/build_script_runner.rs
- lib/app/src/package_build_script_compiler.rs
- lib/app/src/package_builder.rs
- lib/app/src/package_test_builder.rs
- lib/format/Cargo.toml
- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/lib.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/infra/src/ninja_build_script_runner.rs
- tools/run_all_crates.sh
> Keep application files on testing

- doc/docs/references/language/built-ins.md
- doc/docs/references/language/types.md
> Documentation for map entry deletion

- lib/ast-hir/src/module.rs
- lib/ast/src/ast/map_element.rs
- lib/format/src/lib.rs
- lib/hir-mir/src/transformation/map_literal.rs
- lib/hir/src/analysis/expression_visitor.rs
- lib/hir/src/analysis/try_operation_validator.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_coercer.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/hir/src/analysis/type_transformer.rs
- lib/hir/src/analysis/type_visitor.rs
- lib/hir/src/analysis/variable_transformer.rs
- lib/hir/src/ir/map_element.rs
- lib/parse/src/parser.rs
- test/prelude/map.test.pen
> Remove delete entry syntax of map types

- lib/hir/src/analysis/error.rs
- lib/hir/src/analysis/type_checker.rs
- Change error name
- Show missing record field name
> Display missing record field names

- Gemfile.lock
- doc/docs/references/language/built-ins.md
- features/types/map.feature
- lib/hir-mir/src/built_in_call.rs
- lib/hir-mir/src/lib.rs
- lib/hir-mir/src/snapshots/hir_mir__built_in_call__tests__compile_keys.snap
- lib/hir-mir/src/snapshots/hir_mir__built_in_call__tests__compile_values.snap
- lib/hir/src/analysis/built_in_variable_transformer.rs
- lib/hir/src/analysis/type_checker.rs
- lib/hir/src/analysis/type_inferrer.rs
- lib/hir/src/ir/built_in_function.rs
- test/prelude/map.test.pen
> `keys` and `values` built-in functions
